version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shoghl-db
    environment:
      POSTGRES_DB: shoghl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shoghl-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shoghl_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      APPLICATION_SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APPLICATION_SECURITY_JWT_EXPIRATION: 86400000
    depends_on:
      - postgres

volumes:
  postgres_data: